### ISSUE TITLE
Test "owsTests:ows-main" failed validation error via REST API 

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-sos20#36]
Following are the details to reproduce this issue:

* iut: http://sensorweb.demo.52north.org/52n-sos-webapp/service/kvp?service=SOS&request=GetCapabilities
* ets-sos20: Current master
* Teamengine: Current master

There are multiple test failures with the same error when we execute the test via REST API.

```
Caused by: java.lang.RuntimeException: Failed to parse resource from http://sensorweb.demo.52north.org/52n-sos-webapp/service/kvp?service=SOS&request=GetCapabilities
	at com.occamlab.te.parsers.XMLValidatingParser.parse(XMLValidatingParser.java:227)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.occamlab.te.TECore.parse(TECore.java:2168)
	... 387 more
Caused by: org.xml.sax.SAXParseException; systemId: jar:file:/usr/local/tomcat/webapps/teamengine/WEB-INF/lib/ets-sos20-1.14-SNAPSHOT.jar!/xsd/w3c/xml.xsd; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
```

Here is log file: [logs.txt](https://github.com/opengeospatial/ets-sos20/files/3147833/logs.txt)

But if we run this ets via webapp it worked successfully.

**Comment by lgoltz** [comment]
Encoding of file src/main/resources/xsd/w3c/xml.xsd was UTF-16 and the file broken in the jar file. Furthermore an update of the teamengine version was required (bug fix https://github.com/opengeospatial/teamengine/issues/362)
